### ISSUE TITLE
missing rtc modules for RPi CM4 

### ISSUE THREAD

**Issue by ogra1** [snapcore/core-initrd#17]
To set the clock from /dev/rtc0 on a CM4 the rtc-pcf85063 module needs to be in the pi-kernel initrd ... since there are issues with calling hctosys from the kernel at module load time there probably also needs to be a udev rule like:
```
$ cat /etc/udev/rules.d/60-rtc.rules
ACTION=="add", SUBSYSTEM=="rtc", ATTRS{hctosys}=="0", RUN+="/usr/sbin/hwclock -s --utc"
```
and the hwclock binary to set the clock before trying to decrypt/mount the rootfs disk

a corresponding kernel bug has been opened as:

https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1926911

**Comment by rzr** [comment]
May I suggest to also support "rtc-pcf8563.ko" module

I've been trying this module on Pi3:
https://www.olimex.com/Products/Modules/Time/MOD-RTC/open-source-hardware

**Comment by xnox** [comment]
"since there are issues with calling hctosys from the kernel at module load time" is not quite right and the udev rule is quite harmful.

If the rtc is working correctly and it is the only rtc available calling hctosys from the kernel at module load time works correctly.

I am kind of inclined to include all the rtc modules that might be available in the initrd.

**Comment by rzr** [comment]
Hi,
Thanks for feedback but I don't need RTC support anymore
since date is updated from image timestamps
https://forum.snapcraft.io/t/built-uc20-rasperry-pi-image-hangs-on-boot/23891/28?u=rzr
